config/routes.rb
Workshop::Application.routes.draw do
  
  root 'movies#list'

  resources :movies

  post 'filter', to: 'movies#filter'
  get  'filter', to: 'movies#list'

  

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
  has_many :movies

  validates :title, uniqueness: true  
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  description :text
#  rating      :integer
#  category_id :integer
#

class Movie < ActiveRecord::Base
  include OMDB

  belongs_to :category
  has_many :reviews

  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: { in: 2..60 }
  validates :category, presence: true
  validates :rating, inclusion: { in: 1..10, message: "%{value} is not in valid range 1 - 10." }
  validate :sanity

  scope :by_category, -> category { where(category: category) }

  before_create :update_info_from_omdb, :accept_by_jesper
  before_save :accept_by_jesper

  private

  def sanity
    if self.category and self.category.title == "Romantic Comedy" and self.rating > 5
      errors.add("Rating: ","A romantic comedy can't possibly be that good.")
    end
  end

  def accept_by_jesper
    if self.title == "Old Boy"
      self.rating = 10
      self.description = "Best movie ever made"
    end
  end

  def update_info_from_omdb
    result = query_omdb(self.title)

    self.year        = result["Year"]
    self.description = result["Plot"]
    self.poster_uri  = result["Poster"]
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def list
    @movies = Movie.all

    # Specify layout when neccessary.
    # Defaults to app/views/layouts/application.html.erb.
    render layout: "landing"
  end

  def show
    # Use decorators for presentational logic on the model. 
    # Go check out the draper gem.
    @movie = Movie.find(params[:id]).decorate
  end

  def new
    @movie = Movie.new
    @categories = Category.all.map &:title 
  end

  def create
    @movie = Movie.new movie_params
    
    if @movie.save
      # Send flash messages to your views through the flash object
      # or as arguments to redirect_to.
      flash[:alert] = "Tried to fetch additional information from omdb, please edit if incorrect." if @movie.year.present?
      
      redirect_to movie_path(@movie), notice: "Movie was successfully created."
    else
      # Use render over redirect to keep @movie with errors 
      render action: "new"
    end
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    
    if @movie.update movie_params
      redirect_to @movie, notice: "Movie was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    movie = Movie.find(params[:id]).destroy
    redirect_to :root
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :year, :poster_uri, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workshop</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="//use.typekit.net/ubm0jwo.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>

<header>
  <div class="wrapper">
    <h1><%= link_to "Movie Database", root_path %></h1>
    <%= link_to content_tag(:i, '', class: "icon-list"), root_path %>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
  </div>
</header>

<div class="wrapper">
  <%= yield %>
</div>

<footer>
  <div class="wrapper">
    Build with <span class="color">&hearts;</span> at <a href="http://www.ctk.se" class="yellow">CTK</a>.
  </div>
</footer>

<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workshop</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="//use.typekit.net/ubm0jwo.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body class="landing">

<header>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
  <h1>Movies</h1>
</header>

<div class="wrapper">
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>

</body>
</html>

app/views/movies/_detailed_form.erb
<% if @movie.errors.any? %>
  <div id="error_explanation" class="form-error">
    <p><%= pluralize(@movie.errors.count, "error") %> prohibited this post from being saved:</p>
 
    <ol>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
<% end %>

<%= form_for(@movie) do |m| %>
  <%= m.label :title %>
  <%= m.text_field :title, placeholder: "My awesome movie title" %>
  <%= m.label :description %>
  <%= m.text_area :description, placeholder: "Be sure to give as many spoilers as you can" %>
  <%= m.label :rating %>
  <%= m.number_field :rating %>
  <%= m.label :year %>
  <%= m.number_field :year %>
  <%= m.label :poster %>
  <%= m.text_field :poster_uri %>
  <%= m.collection_select :category_id, Category.all,:id, :title %>
  <%= m.submit %>
<% end %>

app/views/movies/_filter_form.html.erb
<%= form_tag(filter_path) do %>
  <%= select_tag :category, options_from_collection_for_select(Category.all, 'id', 'title', params[:category]) %>
  <%= select_tag :rating, options_for_select(1..10, params[:rating]) %>
  <%= submit_tag "Filter" %>
<% end %>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
  <div id="error_explanation" class="form-error">
    <p><%= pluralize(@movie.errors.count, "error") %> prohibited this post from being saved:</p>
 
    <ol>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
<% end %>

<%= form_for(@movie) do |m| %>
  <%= m.label :title %>
  <%= m.text_field :title, placeholder: "My awesome movie title" %>
  <%= m.label :rating %>
  <%= m.number_field :rating %>
  <%= m.collection_select :category_id, Category.all,:id, :title %>
  <%= m.submit %>
<% end %>

app/views/movies/_list.html.erb
<ul>
  <% @movies.each do |movie| %>
    <li>

      <%= button_to movie, method: :delete, class: "delete-button" do %>
        <i class="icon-trash"></i>
      <% end %>
      <%= link_to content_tag(:i, '', class: "icon-edit"), edit_movie_path(movie) %>
      
      <%= link_to movie.title, movie %>
  <% end %>
</ul>

app/views/movies/edit.html.erb
<h1>Edit movie</h1>
<%= render "detailed_form" %>

app/views/movies/index.html.erb
<%= render "filter_form" %>
<%= render "list" %>
<%= link_to "New movie", new_movie_path, class: "button" %>

app/views/movies/list.html.erb
<%= render "list" %>
<%= link_to new_movie_path, class: "button" do %>
  <i class="icon-file push"></i> New movie
<% end %>

app/views/movies/new.html.erb
<h1>New movie</h1>
<%= render "form" %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1 >

<p class="intro">
  <% unless @movie.poster_uri.blank? or @movie.poster_uri == "N/A" %>
    <img src="<%= @movie.poster_uri %>" alt="">
  <% end %>

  <% unless @movie.description.blank? or @movie.description == "N/A" %>
    <%= @movie.description %>
  <% end %>
</p>

<ul>
  <li>Rating: <%= @movie.rating %></li>
  <li>Epicness: This movie is <%= @movie.epicness %>.</li>
  <li>Category: <%= @movie.category.title %></li>
  <% if @movie.year.present? %>
    <li>Year: <%= @movie.year %></li>
  <% end %>
</ul>

<%= link_to edit_movie_path(@movie), class: "button" do %>
  <i class="icon-edit push"></i> Edit movie
<% end %>

<div class="reviews-container">
  <% unless @movie.reviews.empty? %>
    <h2>Reviews</h2>

    <% @movie.reviews.each do |review| %>
      <div class="review">
        <h3><%= review.title %></h3>
        <p>
          <%= review.body %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>